service: lambda-trigger-s3

frameworkVersion: ">=1.1.0"
configValidationMode: error
variablesResolutionMode: null

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-northeast-1
  stackName: matchhat-backend
  memorySize: 512
  timeout: 10
  logRetentionInDays: 1
  deploymentBucket:
    blockPublicAccess: true
    name: matchhat-sls-deployment
    # name: test-matchhat
    # tags:
    #   key1: value1
    #   key2: value2
  deploymentPrefix: serverless

functions:
  lambda-s3-trigger:
    handler: index.handler
    name: ${sls:stage}-image-resizer
    description: resize image after upload
    # role: arn:aws:iam::102431695831:role/lambda-s3-role
    role: arn:aws:iam::307512938321:role/lambda-s3-role
    events:
      - s3:
          # bucket: matchhat-qhkm
          bucket: mhat-dev
          event: s3:ObjectCreated:*
          rules:
            - prefix: avatar/images/raw/
          existing: true
